const express = require("express");
const { userRouter } = require("./user.routers");
const { productRouter } = require("./product.routers");
const { categoryRouter } = require("./category.routers");
const { authorRouter } = require("./author.routers");
const { billRouter } = require("./bill.routers");
const {supplierRouter}= require("./suppliers.routers");
const {cartRouter}=require("./cart.router");
const { discountRouter } = require("./discount.router");
const rootRouter = express.Router();

rootRouter.use("/users", userRouter);
rootRouter.use("/products", productRouter);
rootRouter.use("/categories", categoryRouter);
rootRouter.use("/authors", authorRouter);
rootRouter.use("/bills", billRouter);
rootRouter.use("/suppliers",supplierRouter);
rootRouter.use("/carts",cartRouter);
rootRouter.use("/discounts",discountRouter);
module.exports = { rootRouter };
